num1=int(input("Enter Number1 :" ))
num2=int(input("Enter Number2 : "))
print("Sum is ",num1+num2)
print("Subtraction is ",num1-num2)
print("Multiplication is ",num1*num2)
print("Division is ",num1/num2)
print("Floor Division is ",num1//num2)
print(f"{num1} power {num2} is ",num1**num2)
print("Reminder is ",num1%num2)